In [1]:
import pandas as pd
import numpy as np

In [20]:
cardekho = pd.read_csv('../../data/cleaned_data/cardekho_cleaned_data.csv',index_col=0)

In [21]:
cars24 = pd.read_csv('../../data/cleaned_data/cars24_cleaned_data.csv',index_col = 0)

In [6]:
olx = pd.read_csv('../../data/cleaned_data/olx_listings_delhi.csv',index_col=0)

In [7]:
olx.head()

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand
0,Mercedes-Benz S-Class,https://www.olx.in/item/cars-c84-used-mercedes...,Punjabi Bagh West,13800000,https://apollo.olx.in:443/v1/files/i355lkdgj62...,Petrol,Automatic,2023,12000.0,Mercedes-Benz
1,Hyundai Creta,https://www.olx.in/item/cars-c84-used-hyundai-...,Pitampura,640000,https://apollo.olx.in:443/v1/files/l255s5sei1e...,Petrol,Automatic,2017,90000.0,Hyundai
2,Mercedes-Benz GLA,https://www.olx.in/item/cars-c84-used-mercedes...,Punjabi Bagh West,4200000,https://apollo.olx.in:443/v1/files/4dr78sfcqyj...,Petrol,Automatic,2024,6200.0,Mercedes-Benz
3,Ford Endeavour,https://www.olx.in/item/cars-c84-used-ford-end...,Paschim Vihar,1800000,https://apollo.olx.in:443/v1/files/0k42887kzsj...,Diesel,Automatic,2016,400000.0,Ford
4,BMW 7 Series,https://www.olx.in/item/cars-c84-used-bmw-7-se...,Rajouri Garden,3790000,https://apollo.olx.in:443/v1/files/nanch4yt8k8...,Petrol,Automatic,2016,55000.0,BMW

In [31]:
cars24.head()

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Region Info
0,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",772000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2022,45498,Maruti,HR-98
1,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,Rajouri Garden,590000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2019,93355,Maruti,DL-6C
2,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",899000.0,https://media.cars24.com/hello-ar/dev/transfor...,CNG,Manual,2024,18586,Maruti,HR-14
3,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"Sector-18, Noida",815000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Automatic,2022,33086,Maruti,DL-4C
4,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",450000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2016,96696,Maruti,HR-26

In [28]:
def filter_title(data):
    parts = data.split(" ")
    return " ".join(parts[1:])

In [29]:
cars24['Title'] = cars24['Title'].apply(filter_title)
cardekho['Title'] = cardekho['Title'].apply(filter_title)

In [30]:
cardekho.head()

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Region Info
0,Maruti Suzuki Celerio VXI AT,https://www.cardekho.com/used-car-details/used...,"Badshahpur, Gurgaon",231000.0,https://images10.gaadi.com/usedcar_image/49941...,Petrol,Automatic,2014,60000.0,Maruti,NaN
1,Maruti Suzuki Ciaz Zeta BSIV,https://www.cardekho.com/used-car-details/used...,"Lajpat Nagar, New Delhi",575000.0,https://images10.gaadi.com/usedcar_image/51632...,Petrol,Manual,2019,58000.0,Maruti,NaN
2,Maruti Suzuki Ciaz Delta BSIV,https://www.cardekho.com/used-car-details/used...,"Lajpat Nagar, New Delhi",575000.0,https://images10.gaadi.com/usedcar_image/50705...,Petrol,Manual,2018,41000.0,Maruti,NaN
3,Maruti Suzuki XL6 Alpha AT BSVI,https://www.cardekho.com/buy-used-car-details/...,"Indirapuram, Ghaziabad",1092000.0,https://images10.gaadi.com/usedcar_image/51622...,Petrol,Automatic,2022,53366.0,Maruti,NaN
4,Maruti Suzuki Ertiga 1.5 VDI,https://www.cardekho.com/used-car-details/used...,Greater Noida,830000.0,https://images10.gaadi.com/usedcar_image/50806...,Diesel,Manual,2019,146000.0,Maruti,NaN

In [15]:
olx[olx['Price'] >= 8000000].to_csv('../../data/cleaned_data/olx_luxe_listings_2.csv')

In [16]:
olx = olx[olx['Price'] < 8000000]

In [17]:
olx.shape

(10098, 10)

In [18]:
olx.columns

Index(['Title', 'Link', 'Location', 'Price', 'Image', 'Fuel Type', 'Type',
       'Year', 'Kms Covered', 'Brand'],
      dtype='str')

In [22]:
cars24.columns

Index(['Title', 'Link', 'Price', 'Image', 'Year', 'Brand', 'Location',
       'Kms Covered', 'Fuel Type', 'Type', 'Region Info'],
      dtype='str')

In [23]:
cardekho.columns

Index(['Title', 'Link', 'Price', 'Image', 'Year', 'Brand', 'Location',
       'Kms Covered', 'Fuel Type', 'Type'],
      dtype='str')

In [32]:
all_columns = [
    'Title', 'Link', 'Location', 'Price', 'Image', 'Fuel Type', 'Type',
    'Year', 'Kms Covered', 'Brand', 'Region Info'
]


cardekho = cardekho.reindex(columns=all_columns)
cars24 = cars24.reindex(columns=all_columns)
olx = olx.reindex(columns=all_columns)

# Concatenate them into one dataframe
merged_df = pd.concat([cars24,cardekho,olx], ignore_index=True)

In [33]:
merged_df

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Region Info
0,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",772000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2022,45498.0,Maruti,HR-98
1,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,Rajouri Garden,590000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2019,93355.0,Maruti,DL-6C
2,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",899000.0,https://media.cars24.com/hello-ar/dev/transfor...,CNG,Manual,2024,18586.0,Maruti,HR-14
3,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"Sector-18, Noida",815000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Automatic,2022,33086.0,Maruti,DL-4C
4,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",450000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2016,96696.0,Maruti,HR-26
...,...,...,...,...,...,...,...,...,...,...,...
18236,Kia Seltos,https://www.olx.in/item/cars-c84-used-kia-selt...,Ashok Vihar,785000.0,https://apollo.olx.in:443/v1/files/4e45bl9zlel...,Petrol,Manual,2019,40000.0,Kia,NaN
18237,Kia Sonet,https://www.olx.in/item/cars-c84-used-kia-sone...,Kali Bari Apartment,752000.0,https://apollo.olx.in:443/v1/files/7884zczcnuh...,Diesel,Manual,2021,90210.0,Kia,NaN
18238,Kia Seltos,https://www.olx.in/item/cars-c84-used-kia-selt...,Bakhtawarpur,820000.0,https://apollo.olx.in:443/v1/files/n3ra6o506oo...,Petrol,Manual,2021,23500.0,Kia,NaN
18239,Kia Seltos,https://www.olx.in/item/cars-c84-used-kia-selt...,Siraspur,790000.0,https://apollo.olx.in:443/v1/files/jq63vzkm01n...,Petrol,Manual,2021,23500.0,Kia,NaN
18240,Kia Seltos,https://www.olx.in/item/cars-c84-used-kia-selt...,Siri Fort,1650000.0,https://apollo.olx.in:443/v1/files/jjvjrw1ivm6...,Petrol,Automatic,2023,16000.0,Kia,NaN

In [35]:
merged_df['Type'].unique()

<StringArray>
['Manual', 'Automatic', nan]
Length: 3, dtype: str

In [37]:
merged_df['Fuel Type'].unique()

<StringArray>
['Petrol', 'CNG', 'Diesel', 'Hybrid', nan, 'Electric', 'LPG', 'CNG & Hybrids']
Length: 8, dtype: str

In [42]:
merged_df['Fuel Type'].isna().sum()

np.int64(166)

In [ ]:
import pandas as pd

def indian_format(num):
    s = str(int(num))
    
    r = s[-3:]
    
    l = s[:-3]
   
    while len(l) > 2:
        r = l[-2:] + "," + r
        l = l[:-2]
    if l:
        r = l + "," + r
    return "₹ " + r

# Apply formatting
merged_df["price_display"] = merged_df["Price"].apply(indian_format)

In [46]:
merged_df.head()

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Region Info,price_display
0,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",772000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2022,45498.0,Maruti,HR-98,"₹ 7,72,000"
1,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,Rajouri Garden,590000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2019,93355.0,Maruti,DL-6C,"₹ 5,90,000"
2,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",899000.0,https://media.cars24.com/hello-ar/dev/transfor...,CNG,Manual,2024,18586.0,Maruti,HR-14,"₹ 8,99,000"
3,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"Sector-18, Noida",815000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Automatic,2022,33086.0,Maruti,DL-4C,"₹ 8,15,000"
4,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",450000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2016,96696.0,Maruti,HR-26,"₹ 4,50,000"

In [48]:
merged_df.isna().sum()

Title                0
Link                 0
Location             0
Price                0
Image                1
Fuel Type          166
Type               231
Year                 0
Kms Covered          0
Brand                0
Region Info      17628
price_display        0
dtype: int64

In [52]:
df = merged_df.drop_duplicates().reset_index(drop=True)

In [53]:
df.to_csv('../../data/merged_datasets/merged_ordinary_dataset.csv')

## Handling Luxe Datasets

In [133]:
olx1 = pd.read_csv('../../data/cleaned_data/olx_luxe_listings.csv',index_col = 0)

In [134]:
olx2 = pd.read_csv('../../data/cleaned_data/olx_luxe_listings_2.csv',index_col=0)

In [135]:
crazy = pd.read_csv('../../data/cleaned_data/you_drive_me_crazy_listings.csv',index_col=0)

In [136]:
fusion = pd.read_csv('../../data/cleaned_data/fusion_cars_listings.csv',index_col=0)

In [137]:
olx1.columns

Index(['Title', 'Link', 'Location', 'Price', 'Image', 'Owner', 'Year',
       'Kms Covered', 'Fuel Type', 'Type', 'Brand'],
      dtype='str')

In [138]:
olx2.columns

Index(['Title', 'Link', 'Location', 'Price', 'Image', 'Fuel Type', 'Type',
       'Year', 'Kms Covered', 'Brand'],
      dtype='str')

In [139]:
crazy

,Link,Price,Image,Model,Year,Exterior Color,Interior Color,Registration,Ownership,Brand,Kms Covered,Fuel Type
0,https://youdrivemecrazy.in/listings/jaguar-xj-50/,3500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Jaguar XJ 50,2018,Loire blue,Quilted Ivory white,HP Registered,1,Jaguar,50000,NaN
1,https://youdrivemecrazy.in/listings/porsche-ca...,7200000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Porsche Cayenne 3.0 V6,2019,Biskay blue metallic,Beige,HP Registered,1,Porsche,53000,NaN
2,https://youdrivemecrazy.in/listings/volvo-v90-...,2500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,V90 Cross Country D5,2019,Crystal White,Amber Brown,DL Registered,1,Volvo,78000,Diesel
3,https://youdrivemecrazy.in/listings/lexus-nx300/,2500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,LEXUS NX300,2018,Sonic Quartz,NaN,HR Registered,1,Lexus,137000,NaN
4,https://youdrivemecrazy.in/listings/ford-musta...,7500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,FORD MUSTANG GT 5.0 V8,2017,Magnetic Grey Metallic,Black,HP Registered,1,Ford,27000,NaN
5,https://youdrivemecrazy.in/listings/porsche-pa...,9900000.0,https://youdrivemecrazy.in/wp-content/uploads/...,PORSCHE PANAMERA 4,2020,Jet Black Metallic,NaN,HP Registered,1,Porsche,11000,Petrol
6,https://youdrivemecrazy.in/listings/facelift-t...,2700000.0,https://youdrivemecrazy.in/wp-content/uploads/...,FACELIFT | TITANIUM 2.0 | 4x4,2021,Diamond White,Beige Leather,DL Registered,1,Ford,130000,NaN
7,https://youdrivemecrazy.in/listings/bmw-330i-g...,2550000.0,https://youdrivemecrazy.in/wp-content/uploads/...,330i GT M Sport,2019,Estoril Blue,Black,HR Registered,1,BMW,92000,NaN
8,https://youdrivemecrazy.in/listings/porsche-ca...,3650000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Porsche Cayenne,2013,Moonlight Blue Metallic,Slate Grey,HR Registered,1,Porsche,72000,Petrol
9,https://youdrivemecrazy.in/listings/range-rove...,5800000.0,https://youdrivemecrazy.in/wp-content/uploads/...,SPORT HSE (Facelift),2018,Fuji white,Beige,HR Registered,2,Land Rover,38000,NaN
10,https://youdrivemecrazy.in/listings/rolls-royc...,39100000.0,https://youdrivemecrazy.in/wp-content/uploads/...,GHOST SERIES II XZ42,2017,Madeira RED,Seashell white,DL Registered,1,Rolls royce,58000,Petrol
11,https://youdrivemecrazy.in/listings/bmw-m2-sha...,10500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Bmw M2 Shadow line,2024,Black Sapphire,Ambient interior light,NaN,1,BMW,8000,NaN
12,https://youdrivemecrazy.in/listings/porsche-pa...,11500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Porsche Panamera Bs6,2020,Jet Black Metallic,NaN,HP Registered,1,Porsche,11000,NaN
13,https://youdrivemecrazy.in/listings/z4-m40i-co...,9200000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Z4 M40i Convertible,2024,Black Sapphire Etallic,NaN,HP Registered,1,BMW,4000,NaN
14,https://youdrivemecrazy.in/listings/mercedes-c...,2400000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Mercedes CLA 200 Sport ⚡,2019,Grey,Beige,OD Registered,2,Mercedes,30000,NaN
15,https://youdrivemecrazy.in/listings/mercedes-b...,3950000.0,https://youdrivemecrazy.in/wp-content/uploads/...,MERCEDES-BENZ GLC 43 AMG COUPE,2018,Obsidian Black,NaN,GJ Registered,2,Mercedes,60000,NaN
16,https://youdrivemecrazy.in/listings/jeep-wrang...,6900000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Jeep Wrangler Rubicon 2.0L,2025,Bright White,Custom Tan,HR Registered,1,Jeep,11000,NaN
17,https://youdrivemecrazy.in/listings/jaguar-xk-...,4500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Jaguar XK-R,2012,Emerald green peelable,NaN,CH Registered,1,Jaguar,39000,NaN
18,https://youdrivemecrazy.in/listings/a6-45-tfsi...,3550000.0,https://youdrivemecrazy.in/wp-content/uploads/...,A6 45 TFSI Technology,2020,Mythos Black Metallic,Beige,HP Registered,1,Audi,30000,Petrol
19,https://youdrivemecrazy.in/listings/cooper-s-f...,2250000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Cooper S First lot CBU,2016,NaN,NaN,JH Registered,2,Mini Cooper,62000,Petrol
20,https://youdrivemecrazy.in/listings/nx300-hybr...,2950000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NX300 Hybrid,2018,NaN,NaN,DL Registered,2,Lexus,70000,NaN
21,https://youdrivemecrazy.in/listings/x4-30i-msp...,6100002.0,https://youdrivemecrazy.in/wp-content/uploads/...,X4 30i Msport LCI,2022,Carbon Black Metallic,NaN,MH Registered,1,BMW,22000,Petrol
22,https://youdrivemecrazy.in/listings/e200-lwb-a...,6650000.0,https://youdrivemecrazy.in/wp-content/uploads/...,E200 LWB Amg line,2023,Obsidian Black,Beige,CH Registered,1,Mercedes,8000,Petrol
23,https://youdrivemecrazy.in/listings/q7-technol...,4150000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Q7 Technology 40 TFSI,2018,Galaxy blue,Beige,HR Registered,2,Audi,45000,NaN
24,https://youdrivemecrazy.in/listings/xe-p250-se...,3150000.0,https://youdrivemecrazy.in/wp-content/uploads/...,XE P250 SE (Top Variant),2020,Caldera Red,NaN,HP Registered,1,Jaguar,34000,Petrol
25,https://youdrivemecrazy.in/listings/coopers-jc...,3100000.0,https://youdrivemecrazy.in/wp-content/uploads/...,CooperS JCW tuned Convertible,2018,Deep blue metallic,NaN,JH Registered,2,Mini Cooper,53000,NaN
26,https://youdrivemecrazy.in/listings/a6-35-tfsi/,1775000.0,https://youdrivemecrazy.in/wp-content/uploads/...,A6 35 TFSI,2017,IBIS White,Beige,HR Registered,1,Audi,40000,Petrol
27,https://youdrivemecrazy.in/listings/mercedes-b...,5100000.0,https://youdrivemecrazy.in/wp-content/uploads/...,GLC 200,2022,Cavan-site blue,NaN,HR Registered,1,Mercedes,15000,Petrol
28,https://youdrivemecrazy.in/listings/x5-40i-msp...,9900000.0,https://youdrivemecrazy.in/wp-content/uploads/...,X5 40i Msport LCI,2024,Mineral White,Tartufo,DD Registered,1,BMW,16000,NaN
29,https://youdrivemecrazy.in/listings/a6-s-line-...,2150000.0,https://youdrivemecrazy.in/wp-content/uploads/...,A6 S LINE MATRIX,2017,IBIS White,NaN,HR Registered,1,Audi,63000,Petrol
30,https://youdrivemecrazy.in/listings/xc90-b6-ul...,7500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,XC90 B6 Ultimate Hybrid,2024,Crystal white pearl,NaN,HR Registered,1,Volvo,39000,NaN
31,https://youdrivemecrazy.in/listings/q7-55-tfsi/,6600002.0,https://youdrivemecrazy.in/wp-content/uploads/...,Q7 55 TFSI,2022,Cararra White,OKAPI BROWN,JK Registered,1,Audi,36000,NaN
32,https://youdrivemecrazy.in/listings/x3-30i-msp...,5150000.0,https://youdrivemecrazy.in/wp-content/uploads/...,X3 30i Msport Xdrive,2022,Mineral White,NaN,GJ Registered,1,BMW,34000,NaN
33,https://youdrivemecrazy.in/listings/f-pace-2-0...,3200000.0,https://youdrivemecrazy.in/wp-content/uploads/...,F Pace 2.0L Prestige(Top),2018,Caesium Blue,Beige,HR Registered,2,Jaguar,59000,NaN
34,https://youdrivemecrazy.in/listings/q5-45-tfsi-2/,4999000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Q5 45 TFSI,2024,Glacier white metallic,NaN,HR Registered,1,Audi,37000,Petrol
35,https://youdrivemecrazy.in/listings/tiguan-2-0...,1475000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Tiguan 2.0L TDI-HIGHLINE(AT),2017,Oryx white,NaN,DL Registered,2,Volkswagen,78000,Diesel
36,https://youdrivemecrazy.in/listings/330i-msport/,3950000.0,https://youdrivemecrazy.in/wp-content/uploads/...,330i Msport,2022,Portimao Blue,Mocha,UP Registered,1,BMW,17000,Petrol
37,https://youdrivemecrazy.in/listings/cla-45amg/,2975000.0,https://youdrivemecrazy.in/wp-content/uploads/...,CLA 45AMG,2018,Cirrus White,NaN,DL Registered,2,Mercedes,40000,NaN
38,https://youdrivemecrazy.in/listings/mercedes-a...,7900000.0,https://youdrivemecrazy.in/wp-content/uploads/...,A45 S,2022,Designo Patagonia Red Metallic,NaN,DD Registered,1,Mercedes,26000,NaN
39,https://youdrivemecrazy.in/listings/jaguar-xj-l/,4600000.0,https://youdrivemecrazy.in/wp-content/uploads/...,XJ-L,2017,French Racing Blue,NaN,HP Registered,1,Jaguar,55000,Petrol
40,https://youdrivemecrazy.in/listings/rs5-faceli...,5100000.0,https://youdrivemecrazy.in/wp-content/uploads/...,RS5 Facelift,2013,Sepang Blue,Black,PY Registered,3,Audi,42000,NaN
41,https://youdrivemecrazy.in/listings/jaguar-xk-r/,4500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,XK-R,2012,NaN,NaN,CH Registered,1,Jaguar,38000,NaN
42,https://youdrivemecrazy.in/listings/s-jcw-tuned/,3500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,S JCW Tuned,2018,Midnight Black Metal,Black,HP Registered,1,Mini Cooper,35000,NaN
43,https://youdrivemecrazy.in/listings/range-rove...,5800000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Sport,2018,Fuji white,Beige,HR Registered,2,Land Rover,37000,NaN

In [140]:
fusion.columns

Index(['Title', 'Fuel', 'Price', 'Image_URL', 'URL', 'Year', 'Kms Covered'], dtype='str')

In [141]:
crazy.columns

Index(['Link', 'Price', 'Image', 'Model', 'Year', 'Exterior Color',
       'Interior Color', 'Registration', 'Ownership', 'Brand', 'Kms Covered',
       'Fuel Type'],
      dtype='str')

In [142]:
import pandas as pd
crazy = crazy.rename(columns={
    "Model":"Title"
})
fusion = fusion.rename(columns={
    "Fuel": "Fuel Type",
    "Image_URL": "Image",
    "URL": "Link",

})

olx1 = olx1.rename(columns={
    'Owner':'Ownership'
})

# Step 2: Define master schema
all_columns = [
    'Title', 'Link', 'Location', 'Price', 'Image', 'Fuel Type', 'Type',
    'Year', 'Kms Covered', 'Brand', 'Exterior Color',
    'Interior Color', 'Registration', 'Ownership'
]

# Step 3: Reindex each dataset
olx1 = olx1.reindex(columns=all_columns)
olx2 = olx2.reindex(columns=all_columns)
fusion = fusion.reindex(columns=all_columns)
crazy = crazy.reindex(columns=all_columns)

# Step 4: Concatenate
merged_df = pd.concat([olx1, olx2, fusion, crazy], ignore_index=True)

# Step 5: Add Indian-style price display
def indian_format(num):
    try:
        s = str(int(num))
    except:
        return None
    r = s[-3:]
    l = s[:-3]
    while len(l) > 2:
        r = l[-2:] + "," + r
        l = l[:-2]
    if l:
        r = l + "," + r
    return "₹" + r

merged_df["price_display"] = merged_df["Price"].apply(indian_format)

# Save or inspect
merged_df.to_csv("merged_dataset.csv", index=False)
print(merged_df.head())

                         Title  \
0                  Porsche 911
1  Mercedes-Benz AMG GLE Coupe
2       Land Rover Range Rover
3              Porsche CARRERA
4                       BMW X7

                                                Link        Location  \
0  https://www.olx.in/item/cars-c84-used-porsche-...  Rajouri Garden
1  https://www.olx.in/item/cars-c84-used-mercedes...  Rajouri Garden
2  https://www.olx.in/item/cars-c84-used-land-rov...       Vikaspuri
3  https://www.olx.in/item/cars-c84-used-porsche-...   Paschim Vihar
4  https://www.olx.in/item/cars-c84-used-bmw-x7-i...   Paschim Vihar

        Price                                              Image Fuel Type  \
0  24475000.0  https://apollo.olx.in:443/v1/files/xh2jctgn7oj...    Petrol
1  12900000.0  https://apollo.olx.in:443/v1/files/mta7txri1a2...    Petrol
2  13575000.0  https://apollo.olx.in:443/v1/files/ov1ski0o9ys...    Petrol
3  22975000.0  https://apollo.olx.in:443/v1/files/dbww3copx4l...    Petrol
4   8800000.0  https://apollo.olx.in:443/v1/files/n90pxrsjnnq...    Diesel

        Type    Year  Kms Covered          Brand Exterior Color  \
0        NaN  2025.0        895.0        Porsche            NaN
1  Automatic  2025.0       9700.0  Mercedes-Benz            NaN
2  Automatic  2021.0      52000.0     Land Rover            NaN
3  Automatic  2024.0       2500.0        Porsche            NaN
4  Automatic  2022.0      44000.0            BMW            NaN

  Interior Color Registration  Ownership price_display
0            NaN          NaN        1.0  ₹2,44,75,000
1            NaN          NaN        1.0  ₹1,29,00,000
2            NaN          NaN        1.0  ₹1,35,75,000
3            NaN          NaN        1.0  ₹2,29,75,000
4            NaN          NaN        1.0    ₹88,00,000

In [143]:
merged_df

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Exterior Color,Interior Color,Registration,Ownership,price_display
0,Porsche 911,https://www.olx.in/item/cars-c84-used-porsche-...,Rajouri Garden,24475000.0,https://apollo.olx.in:443/v1/files/xh2jctgn7oj...,Petrol,NaN,2025.0,895.0,Porsche,NaN,NaN,NaN,1.0,"₹2,44,75,000"
1,Mercedes-Benz AMG GLE Coupe,https://www.olx.in/item/cars-c84-used-mercedes...,Rajouri Garden,12900000.0,https://apollo.olx.in:443/v1/files/mta7txri1a2...,Petrol,Automatic,2025.0,9700.0,Mercedes-Benz,NaN,NaN,NaN,1.0,"₹1,29,00,000"
2,Land Rover Range Rover,https://www.olx.in/item/cars-c84-used-land-rov...,Vikaspuri,13575000.0,https://apollo.olx.in:443/v1/files/ov1ski0o9ys...,Petrol,Automatic,2021.0,52000.0,Land Rover,NaN,NaN,NaN,1.0,"₹1,35,75,000"
3,Porsche CARRERA,https://www.olx.in/item/cars-c84-used-porsche-...,Paschim Vihar,22975000.0,https://apollo.olx.in:443/v1/files/dbww3copx4l...,Petrol,Automatic,2024.0,2500.0,Porsche,NaN,NaN,NaN,1.0,"₹2,29,75,000"
4,BMW X7,https://www.olx.in/item/cars-c84-used-bmw-x7-i...,Paschim Vihar,8800000.0,https://apollo.olx.in:443/v1/files/n90pxrsjnnq...,Diesel,Automatic,2022.0,44000.0,BMW,NaN,NaN,NaN,1.0,"₹88,00,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1319,XJ-L,https://youdrivemecrazy.in/listings/jaguar-xj-l/,NaN,4600000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Petrol,NaN,2017.0,55000.0,Jaguar,French Racing Blue,NaN,HP Registered,1.0,"₹46,00,000"
1320,RS5 Facelift,https://youdrivemecrazy.in/listings/rs5-faceli...,NaN,5100000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2013.0,42000.0,Audi,Sepang Blue,Black,PY Registered,3.0,"₹51,00,000"
1321,XK-R,https://youdrivemecrazy.in/listings/jaguar-xk-r/,NaN,4500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2012.0,38000.0,Jaguar,NaN,NaN,CH Registered,1.0,"₹45,00,000"
1322,S JCW Tuned,https://youdrivemecrazy.in/listings/s-jcw-tuned/,NaN,3500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2018.0,35000.0,Mini Cooper,Midnight Black Metal,Black,HP Registered,1.0,"₹35,00,000"
1323,Sport,https://youdrivemecrazy.in/listings/range-rove...,NaN,5800000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2018.0,37000.0,Land Rover,Fuji white,Beige,HR Registered,2.0,"₹58,00,000"

In [145]:
merged_df.isna().sum()

Title                0
Link                 0
Location           521
Price               12
Image                0
Fuel Type           62
Type               632
Year                12
Kms Covered         12
Brand              594
Exterior Color    1283
Interior Color    1301
Registration      1281
Ownership          670
price_display       12
dtype: int64

In [146]:
df = merged_df.dropna(subset=['price_display'])

In [147]:
df

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Exterior Color,Interior Color,Registration,Ownership,price_display
0,Porsche 911,https://www.olx.in/item/cars-c84-used-porsche-...,Rajouri Garden,24475000.0,https://apollo.olx.in:443/v1/files/xh2jctgn7oj...,Petrol,NaN,2025.0,895.0,Porsche,NaN,NaN,NaN,1.0,"₹2,44,75,000"
1,Mercedes-Benz AMG GLE Coupe,https://www.olx.in/item/cars-c84-used-mercedes...,Rajouri Garden,12900000.0,https://apollo.olx.in:443/v1/files/mta7txri1a2...,Petrol,Automatic,2025.0,9700.0,Mercedes-Benz,NaN,NaN,NaN,1.0,"₹1,29,00,000"
2,Land Rover Range Rover,https://www.olx.in/item/cars-c84-used-land-rov...,Vikaspuri,13575000.0,https://apollo.olx.in:443/v1/files/ov1ski0o9ys...,Petrol,Automatic,2021.0,52000.0,Land Rover,NaN,NaN,NaN,1.0,"₹1,35,75,000"
3,Porsche CARRERA,https://www.olx.in/item/cars-c84-used-porsche-...,Paschim Vihar,22975000.0,https://apollo.olx.in:443/v1/files/dbww3copx4l...,Petrol,Automatic,2024.0,2500.0,Porsche,NaN,NaN,NaN,1.0,"₹2,29,75,000"
4,BMW X7,https://www.olx.in/item/cars-c84-used-bmw-x7-i...,Paschim Vihar,8800000.0,https://apollo.olx.in:443/v1/files/n90pxrsjnnq...,Diesel,Automatic,2022.0,44000.0,BMW,NaN,NaN,NaN,1.0,"₹88,00,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1319,XJ-L,https://youdrivemecrazy.in/listings/jaguar-xj-l/,NaN,4600000.0,https://youdrivemecrazy.in/wp-content/uploads/...,Petrol,NaN,2017.0,55000.0,Jaguar,French Racing Blue,NaN,HP Registered,1.0,"₹46,00,000"
1320,RS5 Facelift,https://youdrivemecrazy.in/listings/rs5-faceli...,NaN,5100000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2013.0,42000.0,Audi,Sepang Blue,Black,PY Registered,3.0,"₹51,00,000"
1321,XK-R,https://youdrivemecrazy.in/listings/jaguar-xk-r/,NaN,4500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2012.0,38000.0,Jaguar,NaN,NaN,CH Registered,1.0,"₹45,00,000"
1322,S JCW Tuned,https://youdrivemecrazy.in/listings/s-jcw-tuned/,NaN,3500000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2018.0,35000.0,Mini Cooper,Midnight Black Metal,Black,HP Registered,1.0,"₹35,00,000"
1323,Sport,https://youdrivemecrazy.in/listings/range-rove...,NaN,5800000.0,https://youdrivemecrazy.in/wp-content/uploads/...,NaN,NaN,2018.0,37000.0,Land Rover,Fuji white,Beige,HR Registered,2.0,"₹58,00,000"

In [148]:
df.isna().sum()

Title                0
Link                 0
Location           509
Price                0
Image                0
Fuel Type           50
Type               620
Year                 0
Kms Covered          0
Brand              582
Exterior Color    1271
Interior Color    1289
Registration      1269
Ownership          658
price_display        0
dtype: int64

In [ ]:
df.to_csv('../../data/merged_datasets/merged_luxe_dataset.csv')

## Removing duplicates from merged datasets

In [1]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv('../../data/merged_datasets/merged_luxe_dataset.csv',index_col=0)

In [79]:
df.head()

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Exterior Color,Interior Color,Registration,Ownership,price_display
0,Porsche 911,https://www.olx.in/item/cars-c84-used-porsche-...,Rajouri Garden,24475000.0,https://apollo.olx.in:443/v1/files/xh2jctgn7oj...,Petrol,NaN,2025.0,895.0,Porsche,NaN,NaN,NaN,1.0,"₹2,44,75,000"
1,Mercedes-Benz AMG GLE Coupe,https://www.olx.in/item/cars-c84-used-mercedes...,Rajouri Garden,12900000.0,https://apollo.olx.in:443/v1/files/mta7txri1a2...,Petrol,Automatic,2025.0,9700.0,Mercedes-Benz,NaN,NaN,NaN,1.0,"₹1,29,00,000"
2,Land Rover Range Rover,https://www.olx.in/item/cars-c84-used-land-rov...,Vikaspuri,13575000.0,https://apollo.olx.in:443/v1/files/ov1ski0o9ys...,Petrol,Automatic,2021.0,52000.0,Land Rover,NaN,NaN,NaN,1.0,"₹1,35,75,000"
3,Porsche CARRERA,https://www.olx.in/item/cars-c84-used-porsche-...,Paschim Vihar,22975000.0,https://apollo.olx.in:443/v1/files/dbww3copx4l...,Petrol,Automatic,2024.0,2500.0,Porsche,NaN,NaN,NaN,1.0,"₹2,29,75,000"
4,BMW X7,https://www.olx.in/item/cars-c84-used-bmw-x7-i...,Paschim Vihar,8800000.0,https://apollo.olx.in:443/v1/files/n90pxrsjnnq...,Diesel,Automatic,2022.0,44000.0,BMW,NaN,NaN,NaN,1.0,"₹88,00,000"

In [80]:
df.shape

(1312, 15)

In [82]:
df.head()

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Exterior Color,Interior Color,Registration,Ownership,price_display
0,Porsche 911,https://www.olx.in/item/cars-c84-used-porsche-...,Rajouri Garden,24475000.0,https://apollo.olx.in:443/v1/files/xh2jctgn7oj...,Petrol,NaN,2025.0,895.0,Porsche,NaN,NaN,NaN,1.0,"₹2,44,75,000"
1,Mercedes-Benz AMG GLE Coupe,https://www.olx.in/item/cars-c84-used-mercedes...,Rajouri Garden,12900000.0,https://apollo.olx.in:443/v1/files/mta7txri1a2...,Petrol,Automatic,2025.0,9700.0,Mercedes-Benz,NaN,NaN,NaN,1.0,"₹1,29,00,000"
2,Land Rover Range Rover,https://www.olx.in/item/cars-c84-used-land-rov...,Vikaspuri,13575000.0,https://apollo.olx.in:443/v1/files/ov1ski0o9ys...,Petrol,Automatic,2021.0,52000.0,Land Rover,NaN,NaN,NaN,1.0,"₹1,35,75,000"
3,Porsche CARRERA,https://www.olx.in/item/cars-c84-used-porsche-...,Paschim Vihar,22975000.0,https://apollo.olx.in:443/v1/files/dbww3copx4l...,Petrol,Automatic,2024.0,2500.0,Porsche,NaN,NaN,NaN,1.0,"₹2,29,75,000"
4,BMW X7,https://www.olx.in/item/cars-c84-used-bmw-x7-i...,Paschim Vihar,8800000.0,https://apollo.olx.in:443/v1/files/n90pxrsjnnq...,Diesel,Automatic,2022.0,44000.0,BMW,NaN,NaN,NaN,1.0,"₹88,00,000"

In [84]:
from urllib.parse import urlparse

df['Platform'] = df['Link'].apply(lambda x: urlparse(x).netloc.replace('www.', ''))

olx_df = df[df['Platform'].str.contains('olx', case=False, na=False)]

olx_df = olx_df.drop_duplicates(subset=['Image','Year','Title','Price','Kms Covered'])

non_olx_df = df[~df['Platform'].str.contains('olx', case=False, na=False)]

cleaned_df = pd.concat([non_olx_df, olx_df], ignore_index=True)

print(cleaned_df)

                                           Title  \
0        2022/23 LAND ROVER DEFENDER 2.0 HSE 110
1     2015/16 LAMBORGHINI HURACAN COUPE LP 610-4
2                  2022/23 MINI COOPER SE 3 DOOR
3                2024/25 TOYOTA LAND CRUISER 300
4          2022 MERCEDES BENZ EQS 53 AMG 4MATIC+
...                                          ...
1086                                      BMW X5
1087                                      BMW X7
1088                                      BMW X7
1089                                      BMW X7
1090                                      BMW X7

                                                   Link  \
0     https://fusioncars.in/cars/2025-range-rover-ve...
1     https://fusioncars.in/cars/2015-16-lamborghini...
2     https://fusioncars.in/cars/2017-18-mini-cooper...
3     https://fusioncars.in/cars/2023-toyota-fortune...
4     https://fusioncars.in/cars/2024-26-mercedes-be...
...                                                 ...
1086  https://www.olx.in/item/cars-c84-used-bmw-x5-i...
1087  https://www.olx.in/item/cars-c84-used-bmw-x7-i...
1088  https://www.olx.in/item/cars-c84-used-bmw-x7-i...
1089  https://www.olx.in/item/cars-c84-used-bmw-x7-i...
1090  https://www.olx.in/item/cars-c84-used-bmw-x7-i...

                      Location       Price  \
0                          NaN   9800000.0
1                          NaN  23800000.0
2                          NaN   3400000.0
3                          NaN  23500000.0
4                          NaN  12500000.0
...                        ...         ...
1086         Punjabi Bagh West   9700000.0
1087                 Vikaspuri   9200000.0
1088           Noida Extension   9200000.0
1089                IMT Rohtak   9200000.0
1090  Faridabad (New Township)   9200000.0

                                                  Image Fuel Type       Type  \
0     data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0...    Petrol        NaN
1     data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0...    Petrol        NaN
2     data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0...  Electric        NaN
3     data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0...    Petrol        NaN
4     data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0...  Electric        NaN
...                                                 ...       ...        ...
1086  https://apollo.olx.in:443/v1/files/5hqt1lqtkp5...    Petrol        NaN
1087  https://apollo.olx.in:443/v1/files/4q189bd32jv...    Petrol  Automatic
1088  https://apollo.olx.in:443/v1/files/pc0jemq2cah...    Petrol  Automatic
1089  https://apollo.olx.in:443/v1/files/usnse8lgruj...    Petrol  Automatic
1090  https://apollo.olx.in:443/v1/files/xuieklsa5as...    Petrol  Automatic

        Year  Kms Covered Brand Exterior Color Interior Color Registration  \
0     2023.0      34000.0   NaN            NaN            NaN          NaN
1     2016.0      18000.0   NaN            NaN            NaN          NaN
2     2023.0       5000.0   NaN            NaN            NaN          NaN
3     2025.0       7000.0   NaN            NaN            NaN          NaN
4     2022.0       9000.0   NaN            NaN            NaN          NaN
...      ...          ...   ...            ...            ...          ...
1086  2025.0       3300.0   BMW            NaN            NaN          NaN
1087  2023.0      68000.0   BMW            NaN            NaN          NaN
1088  2023.0      39387.0   BMW            NaN            NaN          NaN
1089  2023.0      39387.0   BMW            NaN            NaN          NaN
1090  2023.0      39387.0   BMW            NaN            NaN          NaN

      Ownership price_display       Platform
0           NaN    ₹98,00,000  fusioncars.in
1           NaN  ₹2,38,00,000  fusioncars.in
2           NaN    ₹34,00,000  fusioncars.in
3           NaN  ₹2,35,00,000  fusioncars.in
4           NaN  ₹1,25,00,000  fusioncars.in
...         ...           ...            ...
1086        NaN    ₹97,00,000         olx.in
1087        NaN    ₹92,00,000         olx.in
1088        NaN    ₹92,00,000         olx.in
1089        NaN    ₹92,00,000         olx.in
1090        NaN    ₹92,00,000         olx.in

[1091 rows x 16 columns]

In [86]:
cleaned_df.to_csv('../../data/merged_datasets/merged_luxe_dataset.csv')

In [90]:
df = pd.read_csv('../../data/merged_datasets/merged_ordinary_dataset.csv',index_col=0)

In [91]:
df.head()

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Region Info,price_display
0,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",772000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2022,45498.0,Maruti,HR-98,"₹ 7,72,000"
1,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,Rajouri Garden,590000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2019,93355.0,Maruti,DL-6C,"₹ 5,90,000"
2,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",899000.0,https://media.cars24.com/hello-ar/dev/transfor...,CNG,Manual,2024,18586.0,Maruti,HR-14,"₹ 8,99,000"
3,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"Sector-18, Noida",815000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Automatic,2022,33086.0,Maruti,DL-4C,"₹ 8,15,000"
4,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",450000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2016,96696.0,Maruti,HR-26,"₹ 4,50,000"

In [102]:
df.duplicated(subset=['Image','Year','Title','Price','Kms Covered','Location','Brand','Type']).sum()

np.int64(2226)

In [103]:
df = df.drop_duplicates(subset=['Image','Year','Title','Price','Kms Covered','Location','Brand','Type']).reset_index(drop= True)

In [104]:
df

,Title,Link,Location,Price,Image,Fuel Type,Type,Year,Kms Covered,Brand,Region Info,price_display
0,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",772000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2022,45498.0,Maruti,HR-98,"₹ 7,72,000"
1,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,Rajouri Garden,590000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2019,93355.0,Maruti,DL-6C,"₹ 5,90,000"
2,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",899000.0,https://media.cars24.com/hello-ar/dev/transfor...,CNG,Manual,2024,18586.0,Maruti,HR-14,"₹ 8,99,000"
3,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"Sector-18, Noida",815000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Automatic,2022,33086.0,Maruti,DL-4C,"₹ 8,15,000"
4,Maruti Ertiga,https://www.cars24.com/buy-used-maruti-ertiga-...,"M3M Urbana, Golf Course Ext., Gurugram",450000.0,https://media.cars24.com/hello-ar/dev/transfor...,Petrol,Manual,2016,96696.0,Maruti,HR-26,"₹ 4,50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...
13751,Kia Sonet,https://www.olx.in/item/cars-c84-used-kia-sone...,Karol Bagh,820000.0,https://apollo.olx.in:443/v1/files/oqw4034n1zi...,Diesel,Automatic,2021,65000.0,Kia,NaN,"₹ 8,20,000"
13752,Kia Seltos,https://www.olx.in/item/cars-c84-used-kia-selt...,Ashok Vihar,785000.0,https://apollo.olx.in:443/v1/files/4e45bl9zlel...,Petrol,Manual,2019,40000.0,Kia,NaN,"₹ 7,85,000"
13753,Kia Sonet,https://www.olx.in/item/cars-c84-used-kia-sone...,Kali Bari Apartment,752000.0,https://apollo.olx.in:443/v1/files/7884zczcnuh...,Diesel,Manual,2021,90210.0,Kia,NaN,"₹ 7,52,000"
13754,Kia Seltos,https://www.olx.in/item/cars-c84-used-kia-selt...,Bakhtawarpur,820000.0,https://apollo.olx.in:443/v1/files/n3ra6o506oo...,Petrol,Manual,2021,23500.0,Kia,NaN,"₹ 8,20,000"
13755,Kia Seltos,https://www.olx.in/item/cars-c84-used-kia-selt...,Siraspur,790000.0,https://apollo.olx.in:443/v1/files/jq63vzkm01n...,Petrol,Manual,2021,23500.0,Kia,NaN,"₹ 7,90,000"

In [106]:
df.to_csv('../../data/merged_datasets/merged_ordinary_dataset.csv')